<script context="module">
  export async function load({ fetch, params }) {
    const response = await fetch(`/api/students/${params.id}`)
    const result = response.ok && (await response.json())
    return {
      status: response.status,
      props: {
        student: result.student,
        errors: result.errors,
      },
    }
  }
</script>

<script>
  import { notifications } from '$lib/notifications/index.js'
  import { students as store, schoolYears } from '$lib/data/stores.js'
  import { client } from '$lib/data/fetch-client.js'
  import { goto } from '$app/navigation'
  import Error from '$lib/Error.svelte'
  import Input from '$lib/Input.svelte'
  import Form from '$lib/Form.svelte'
  import StudentGroupSelect from '../_StudentGroupSelect.svelte'
  import DeleteStudent from './_DeleteStudent.svelte'
  // import DeleteGroup from './_DeleteGroup.svelte'

  export let student
  export let errors
  let groupId
  let {
    commonName,
    id,
    birthdate,
    idName,
    gender,
    groups,
    chineseName,
    pinyinName,
    nationality,
    englishName,
    languages,
  } = student

  console.log(student)
  const onSubmit = async () => {
    const response = await client(
      `/api/students/${id}`,
      {
        id,
        commonName,
        idName,
        chineseName,
        englishName,
        languages,
        gender,
        groupId,
        nationality,
        pinyinName,
        birthdate,
      },
      'PATCH',
    )
    const cleanStore = $store.filter(s => s.id !== id)
    store.set([...cleanStore, response.student])

    notifications.add({
      type: 'success',
      text: `Saved student ${name}`,
    })
    goto('/students')
  }
  const onReset = () => {
    ;({
      commonName,
      birthdate,
      idName,
      chineseName,
      pinyinName,
      groups,
      englishName,
      languages,
      gender,
      nationality,
    } = student)
  }

  const makePinyin = async () => {
    if (chineseName && !pinyinName) {
      const response = await fetch(`/api/pinyin/${chineseName}`)
      const result = response.ok && (await response.json())
      pinyinName = result.pinyin
    }
  }
  if (groups && $schoolYears) {
    groupId = groups?.find(
      group => group.schoolYearId === $schoolYears.active,
    ).id
  }
</script>

<h1>Edit student</h1>

<Error {errors} />

{#if student}
  <Form {onSubmit} {onReset} onError={onReset} submitLabel="Save changes">
    <Input
      bind:value={commonName}
      label="Common name"
      description="What the student is called in class, Bruce"
      required
    />
    <Input
      bind:value={idName}
      label="ID name"
      description="As written on passport or other ID"
    />
    <Input
      bind:value={chineseName}
      label="Chinese Name"
      onChange={makePinyin}
      description="In Chinese characters, like 李小龙"
    />
    <Input
      bind:value={pinyinName}
      label="Pinyin Name"
      description="edit if not autogenerated correctly"
    />
    <Input
      bind:value={englishName}
      label="English Name"
      description="May be same as ID name, like Bruce Lee"
    />
    <Input
      bind:value={nationality}
      label="Nationality"
      description="According to ID documents"
    />
    <Input
      bind:value={languages}
      label="Languages"
      description="Languages other than English the student uses"
    />
    <Input bind:value={birthdate} label="Birthdate" type="date" />
    <StudentGroupSelect bind:groupId />
    <h3>Gender</h3>
    <div class="form-control w-24">
      <label class="label cursor-pointer">
        <span class="label-text">Male</span>
        <input
          type="radio"
          bind:group={gender}
          name="gender"
          value="M"
          class="radio checked:bg-blue-500"
        />
      </label>

      <label class="label cursor-pointer">
        <span class="label-text">Female</span>
        <input
          type="radio"
          bind:group={gender}
          name="gender"
          value="F"
          class="radio checked:bg-red-500"
        />
      </label>
    </div>
    <input hidden value={id} name="id" />
  </Form>
  <DeleteStudent {id} />
{:else}
  <p>loading group</p>
{/if}
