<script>
  import { notifications } from '$lib/notifications/index.js'
  import { students } from '$lib/data/students.js'
  import { activeGroups } from '$lib/data/groups.js'
  import { goto } from '$app/navigation'
  import Input from '$lib/Input.svelte'
  import Form from '$lib/Form.svelte'
  import StudentGroupSelect from '$lib/StudentGroupSelect.svelte'
  import DeleteStudent from '../_DeleteStudent.svelte'
  import EditGuardians from '../_EditGuardians.svelte'

  export let data = {}
  const { id } = data
  let student = $students.find((s) => s.id === id)

  let groupId = student.groups.find((group) =>
    $activeGroups.find((g) => g.id === group.id),
  )?.id

  const onSubmit = async () => {
    const { groups, guardians, createdAt, updatedAt, ...cleanStudent } = student
    students.patch({ ...cleanStudent, groupId })
    notifications.add({
      type: 'success',
      text: `Saved student ${name}`,
    })
    goto('/students')
  }
  const onReset = () => {
    student = $students.find((s) => s.id === id)
  }

  const makePinyin = async () => {
    if (student.chineseName && !student.pinyinName) {
      const response = await fetch(`/api/pinyin/${student.chineseName}`)
      const result = response.ok && (await response.json())
      student.pinyinName = result.pinyin
    }
  }
</script>

<h1>Edit student</h1>

{#if student}
  <Form {onSubmit} {onReset} submitLabel="Save changes">
    <Input
      bind:value={student.commonName}
      label="Common name"
      description="What the student is called in class, Bruce"
      required
    />
    <Input
      bind:value={student.idName}
      label="ID name"
      description="As written on passport or other ID"
    />
    <Input
      bind:value={student.chineseName}
      label="Chinese Name"
      onChange={makePinyin}
      description="In Chinese characters, like 李小龙"
    />
    <Input
      bind:value={student.pinyinName}
      label="Pinyin Name"
      description="edit if not autogenerated correctly"
    />
    <Input
      bind:value={student.englishName}
      label="English Name"
      description="May be same as ID name, like Bruce Lee"
    />
    <Input
      bind:value={student.nationality}
      label="Nationality"
      description="According to ID documents"
    />
    <Input
      bind:value={student.languages}
      label="Languages"
      description="Languages other than English the student uses"
    />
    <Input bind:value={student.birthdate} label="Birthdate" type="date" />
    <StudentGroupSelect bind:groupId />
    <h3>Gender</h3>
    <div class="form-control w-24">
      <label class="label cursor-pointer">
        <span class="label-text">Male</span>
        <input
          type="radio"
          bind:group={student.gender}
          name="gender"
          value="M"
          class="radio checked:bg-blue-500"
        />
      </label>

      <label class="label cursor-pointer">
        <span class="label-text">Female</span>
        <input
          type="radio"
          bind:group={student.gender}
          name="gender"
          value="F"
          class="radio checked:bg-red-500"
        />
      </label>
    </div>
    <input hidden value={student.id} name="id" />
  </Form>
  <EditGuardians id={student.id} />
  <DeleteStudent id={student.id} />
{:else}
  <p>loading student</p>
{/if}
